In [1]:
import pandas as pd

df1 = pd.DataFrame({'a': ['a0', 'a1', 'a2', 'a3'], 'b': ['b0', 'b1', 'b2', 'b3'], 'c': ['c0', 'c1', 'c2', 'c3']}, index=[0,1,2,3])
df2 = pd.DataFrame({'a': ['a2', 'a3', 'a4', 'a5'], 'b': ['b2', 'b3', 'b4', 'b5'], 'c': ['c2', 'c3', 'c4', 'c5'], 'd': ['d2', 'd3', 'd4', 'd5']}, index=[2, 3, 4, 5])
print(df1)
print()
print(df2)

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3

    a   b   c   d
2  a2  b2  c2  d2
3  a3  b3  c3  d3
4  a4  b4  c4  d4
5  a5  b5  c5  d5

In [2]:
result = pd.concat([df1, df2])
result

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
2  a2  b2  c2   d2
3  a3  b3  c3   d3
4  a4  b4  c4   d4
5  a5  b5  c5   d5

In [3]:
# 인덱스 무시하고 재배열
result2 = pd.concat([df1, df2], ignore_index=True)
result2

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
4  a2  b2  c2   d2
5  a3  b3  c3   d3
6  a4  b4  c4   d4
7  a5  b5  c5   d5

In [4]:
result3 = pd.concat([df1, df2], join='inner')
result3

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3
2  a2  b2  c2
3  a3  b3  c3
4  a4  b4  c4
5  a5  b5  c5

In [5]:
result4 = pd.concat([df1, df2], axis=1)
result4

     a    b    c    a    b    c    d
0   a0   b0   c0  NaN  NaN  NaN  NaN
1   a1   b1   c1  NaN  NaN  NaN  NaN
2   a2   b2   c2   a2   b2   c2   d2
3   a3   b3   c3   a3   b3   c3   d3
4  NaN  NaN  NaN   a4   b4   c4   d4
5  NaN  NaN  NaN   a5   b5   c5   d5

In [6]:
result5 = pd.concat([df1, df2], axis=1, join='inner')
result5

    a   b   c   a   b   c   d
2  a2  b2  c2  a2  b2  c2  d2
3  a3  b3  c3  a3  b3  c3  d3

In [7]:
sr1 = pd.Series(['e0', 'e1', 'e2', 'e3'])
sr2 = pd.Series(['f0', 'f1', 'f2', 'f3'], name='f')
sr3 = pd.Series(['g0', 'g1', 'g2'], name='g', index=[2, 3, 4])
print(sr1)
print()
print(sr2)
print()
print(sr3)

0    e0
1    e1
2    e2
3    e3
dtype: object

0    f0
1    f1
2    f2
3    f3
Name: f, dtype: object

2    g0
3    g1
4    g2
Name: g, dtype: object

In [8]:
result6 = pd.concat([df1, sr1])
result6

     a    b    c    0
0   a0   b0   c0  NaN
1   a1   b1   c1  NaN
2   a2   b2   c2  NaN
3   a3   b3   c3  NaN
0  NaN  NaN  NaN   e0
1  NaN  NaN  NaN   e1
2  NaN  NaN  NaN   e2
3  NaN  NaN  NaN   e3

In [9]:
result7 = pd.concat([df1, sr2])
result7

     a    b    c    0
0   a0   b0   c0  NaN
1   a1   b1   c1  NaN
2   a2   b2   c2  NaN
3   a3   b3   c3  NaN
0  NaN  NaN  NaN   f0
1  NaN  NaN  NaN   f1
2  NaN  NaN  NaN   f2
3  NaN  NaN  NaN   f3

In [10]:
result8 = pd.concat([df1, sr3])
result8

     a    b    c    0
0   a0   b0   c0  NaN
1   a1   b1   c1  NaN
2   a2   b2   c2  NaN
3   a3   b3   c3  NaN
2  NaN  NaN  NaN   g0
3  NaN  NaN  NaN   g1
4  NaN  NaN  NaN   g2

In [11]:
result9 = pd.concat([df1, sr1], axis=1)
result9

    a   b   c   0
0  a0  b0  c0  e0
1  a1  b1  c1  e1
2  a2  b2  c2  e2
3  a3  b3  c3  e3

In [12]:
result10 = pd.concat([df1, sr2], axis=1)
result10

    a   b   c   f
0  a0  b0  c0  f0
1  a1  b1  c1  f1
2  a2  b2  c2  f2
3  a3  b3  c3  f3

In [13]:
result11 = pd.concat([df1, sr3], axis=1)
result11

     a    b    c    g
0   a0   b0   c0  NaN
1   a1   b1   c1  NaN
2   a2   b2   c2   g0
3   a3   b3   c3   g1
4  NaN  NaN  NaN   g2

In [19]:
result12 = pd.concat([sr1, sr2])
result15 = pd.concat([sr1, sr2], axis=1)
print(result12)
print()
print(result15)

0    e0
1    e1
2    e2
3    e3
0    f0
1    f1
2    f2
3    f3
dtype: object

    0   f
0  e0  f0
1  e1  f1
2  e2  f2
3  e3  f3

In [20]:
result13 = pd.concat([sr1, sr3])
result16 = pd.concat([sr1, sr3], axis=1)
print(result13)
print()
print(result16)

0    e0
1    e1
2    e2
3    e3
2    g0
3    g1
4    g2
dtype: object

     0    g
0   e0  NaN
1   e1  NaN
2   e2   g0
3   e3   g1
4  NaN   g2

In [21]:
result14 = pd.concat([sr2, sr3])
result17 = pd.concat([sr2, sr3], axis=1)
print(result14)
print()
print(result17)

0    f0
1    f1
2    f2
3    f3
2    g0
3    g1
4    g2
dtype: object

     f    g
0   f0  NaN
1   f1  NaN
2   f2   g0
3   f3   g1
4  NaN   g2

In [23]:
# 병합 : merge()

pd.set_option('display.max_columns', 10)
pd.set_option('display.max_colwidth', 20)
pd.set_option('display.unicode.east_asian_width', True)

df1 = pd.read_excel('/content/stockprice.xlsx')
df2 = pd.read_excel('/content/stockvaluation.xlsx')

print(df1)
print()
print(df2)

       id    stock_name          value   price
0  128940      한미약품   59385.666667  421000
1  130960        CJ E&M   58540.666667   98900
2  138250    엔에스쇼핑   14558.666667   13200
3  139480        이마트  239230.833333  254500
4  142280  녹십자엠에스     468.833333   10200
5  145990        삼양사   82750.000000   82000
6  185750        종근당   40293.666667  100500
7  192400    쿠쿠홀딩스  179204.666667  177500
8  199800          툴젠   -2514.333333  115400
9  204210  모두투어리츠    3093.333333    3475

       id              name           eps     bps        per       pbr
0  130960            CJ E&M   6301.333333   54068  15.695091  1.829178
1  136480              하림    274.166667    3551  11.489362  0.887074
2  138040    메리츠금융지주   2122.333333   14894   6.313806  0.899691
3  139480            이마트  18268.166667  295780  13.931338  0.860437
4  145990            삼양사   5741.000000  108090  14.283226  0.758627
5  161390        한국타이어   5648.500000   51341   7.453306  0.820007
6  181710   NHN엔터테인먼트   2110.166667   78434  30.755864  0.827447
7  185750            종근당   3990.333333   40684  25.185866  2.470259
8  204210      모두투어리츠     85.166667    5335  40.802348  0.651359
9  207940  삼성바이오로직스   4644.166667   60099  89.790059  6.938551

In [24]:
merge_inner = pd.merge(df1, df2)
merge_inner

,id,stock_name,value,price,name,eps,bps,per,pbr
0,130960,CJ E&M,58540.666667,98900,CJ E&M,6301.333333,54068,15.695091,1.829178
1,139480,이마트,239230.833333,254500,이마트,18268.166667,295780,13.931338,0.860437
2,145990,삼양사,82750.000000,82000,삼양사,5741.000000,108090,14.283226,0.758627
3,185750,종근당,40293.666667,100500,종근당,3990.333333,40684,25.185866,2.470259
4,204210,모두투어리츠,3093.333333,3475,모두투어리츠,85.166667,5335,40.802348,0.651359

In [25]:
merge_outer = pd.merge(df1, df2, how='outer', on='id')
merge_outer

,id,stock_name,value,price,name,eps,bps,per,pbr
0,128940,한미약품,59385.666667,421000.0,NaN,NaN,NaN,NaN,NaN
1,130960,CJ E&M,58540.666667,98900.0,CJ E&M,6301.333333,54068.0,15.695091,1.829178
2,138250,엔에스쇼핑,14558.666667,13200.0,NaN,NaN,NaN,NaN,NaN
3,139480,이마트,239230.833333,254500.0,이마트,18268.166667,295780.0,13.931338,0.860437
4,142280,녹십자엠에스,468.833333,10200.0,NaN,NaN,NaN,NaN,NaN
5,145990,삼양사,82750.000000,82000.0,삼양사,5741.000000,108090.0,14.283226,0.758627
6,185750,종근당,40293.666667,100500.0,종근당,3990.333333,40684.0,25.185866,2.470259
7,192400,쿠쿠홀딩스,179204.666667,177500.0,NaN,NaN,NaN,NaN,NaN
8,199800,툴젠,-2514.333333,115400.0,NaN,NaN,NaN,NaN,NaN
9,204210,모두투어리츠,3093.333333,3475.0,모두투어리츠,85.166667,5335.0,40.802348,0.651359
10,136480,NaN,NaN,NaN,하림,274.166667,3551.0,11.489362,0.887074
11,138040,NaN,NaN,NaN,메리츠금융지주,2122.333333,14894.0,6.313806,0.899691
12,161390,NaN,NaN,NaN,한국타이어,5648.500000,51341.0,7.453306,0.820007
13,181710,NaN,NaN,NaN,NHN엔터테인먼트,2110.166667,78434.0,30.755864,0.827447
14,207940,NaN,NaN,NaN,삼성바이오로직스,4644.166667,60099.0,89.790059,6.938551

In [26]:
merge_left = pd.merge(df1, df2, how='left', left_on='stock_name', right_on='name')
merge_left

,id_x,stock_name,value,price,id_y,name,eps,bps,per,pbr
0,128940,한미약품,59385.666667,421000,NaN,NaN,NaN,NaN,NaN,NaN
1,130960,CJ E&M,58540.666667,98900,130960.0,CJ E&M,6301.333333,54068.0,15.695091,1.829178
2,138250,엔에스쇼핑,14558.666667,13200,NaN,NaN,NaN,NaN,NaN,NaN
3,139480,이마트,239230.833333,254500,139480.0,이마트,18268.166667,295780.0,13.931338,0.860437
4,142280,녹십자엠에스,468.833333,10200,NaN,NaN,NaN,NaN,NaN,NaN
5,145990,삼양사,82750.000000,82000,145990.0,삼양사,5741.000000,108090.0,14.283226,0.758627
6,185750,종근당,40293.666667,100500,185750.0,종근당,3990.333333,40684.0,25.185866,2.470259
7,192400,쿠쿠홀딩스,179204.666667,177500,NaN,NaN,NaN,NaN,NaN,NaN
8,199800,툴젠,-2514.333333,115400,NaN,NaN,NaN,NaN,NaN,NaN
9,204210,모두투어리츠,3093.333333,3475,204210.0,모두투어리츠,85.166667,5335.0,40.802348,0.651359

In [27]:
merge_right = pd.merge(df1, df2, how='right', left_on='stock_name', right_on='name')
merge_right

,id_x,stock_name,value,price,id_y,name,eps,bps,per,pbr
0,130960.0,CJ E&M,58540.666667,98900.0,130960,CJ E&M,6301.333333,54068,15.695091,1.829178
1,NaN,NaN,NaN,NaN,136480,하림,274.166667,3551,11.489362,0.887074
2,NaN,NaN,NaN,NaN,138040,메리츠금융지주,2122.333333,14894,6.313806,0.899691
3,139480.0,이마트,239230.833333,254500.0,139480,이마트,18268.166667,295780,13.931338,0.860437
4,145990.0,삼양사,82750.000000,82000.0,145990,삼양사,5741.000000,108090,14.283226,0.758627
5,NaN,NaN,NaN,NaN,161390,한국타이어,5648.500000,51341,7.453306,0.820007
6,NaN,NaN,NaN,NaN,181710,NHN엔터테인먼트,2110.166667,78434,30.755864,0.827447
7,185750.0,종근당,40293.666667,100500.0,185750,종근당,3990.333333,40684,25.185866,2.470259
8,204210.0,모두투어리츠,3093.333333,3475.0,204210,모두투어리츠,85.166667,5335,40.802348,0.651359
9,NaN,NaN,NaN,NaN,207940,삼성바이오로직스,4644.166667,60099,89.790059,6.938551

In [28]:
df1[df1['price'] < 50000]

       id    stock_name         value  price
2  138250    엔에스쇼핑  14558.666667  13200
4  142280  녹십자엠에스    468.833333  10200
9  204210  모두투어리츠   3093.333333   3475

In [29]:
price = df1[df1['price'] < 50000]
value = pd.merge(price, df2)
value

,id,stock_name,value,price,name,eps,bps,per,pbr
0,204210,모두투어리츠,3093.333333,3475,모두투어리츠,85.166667,5335,40.802348,0.651359

In [32]:
# join()

pd.set_option('display.max_columns', 10)
pd.set_option('display.max_colwidth', 20)
pd.set_option('display.unicode.east_asian_width', True)

df1 = pd.read_excel('/content/stockprice.xlsx', index_col='id')
df2 = pd.read_excel('/content/stockvaluation.xlsx', index_col='id')

df3 = df1.join(df2, how='inner')
df3

,stock_name,value,price,name,eps,bps,per,pbr
id,,,,,,,,
130960,CJ E&M,58540.666667,98900,CJ E&M,6301.333333,54068,15.695091,1.829178
139480,이마트,239230.833333,254500,이마트,18268.166667,295780,13.931338,0.860437
145990,삼양사,82750.000000,82000,삼양사,5741.000000,108090,14.283226,0.758627
185750,종근당,40293.666667,100500,종근당,3990.333333,40684,25.185866,2.470259
204210,모두투어리츠,3093.333333,3475,모두투어리츠,85.166667,5335,40.802348,0.651359

In [34]:
# groupby()

import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age', 'sex', 'class', 'fare', 'survived']]
df.head()

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

In [35]:
grouped = df.groupby(['class'])
grouped

In [37]:
for key, group in grouped:
    print('key :', key)
    print('number :', len(group))
    print(group.head())
    print()

key : First
number : 216
     age     sex  class     fare  survived
1   38.0  female  First  71.2833         1
3   35.0  female  First  53.1000         1
6   54.0    male  First  51.8625         0
11  58.0  female  First  26.5500         1
23  28.0    male  First  35.5000         1

key : Second
number : 184
     age     sex   class     fare  survived
9   14.0  female  Second  30.0708         1
15  55.0  female  Second  16.0000         1
17   NaN    male  Second  13.0000         1
20  35.0    male  Second  26.0000         0
21  34.0    male  Second  13.0000         1

key : Third
number : 491
    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
2  26.0  female  Third   7.9250         1
4  35.0    male  Third   8.0500         0
5   NaN    male  Third   8.4583         0
7   2.0    male  Third  21.0750         0

<ipython-input-37-ebae1bf0386f>:1: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for key, group in grouped:

In [38]:
average = grouped.mean()
average

<ipython-input-38-d7aac1483e26>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  average = grouped.mean()

              age       fare  survived
class
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

In [41]:
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age', 'sex', 'class', 'fare', 'survived']]
grouped = df.groupby(['class'])

group1 = grouped.get_group('Third')
group1.head()

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
2  26.0  female  Third   7.9250         1
4  35.0    male  Third   8.0500         0
5   NaN    male  Third   8.4583         0
7   2.0    male  Third  21.0750         0

In [42]:
grouped_two = df.groupby(['class', 'sex'])
for key, group in grouped_two:
    print('key :', key)
    print('number :', len(group))
    print(group.head())
    print()

key : ('First', 'female')
number : 94
     age     sex  class      fare  survived
1   38.0  female  First   71.2833         1
3   35.0  female  First   53.1000         1
11  58.0  female  First   26.5500         1
31   NaN  female  First  146.5208         1
52  49.0  female  First   76.7292         1

key : ('First', 'male')
number : 122
     age   sex  class      fare  survived
6   54.0  male  First   51.8625         0
23  28.0  male  First   35.5000         1
27  19.0  male  First  263.0000         0
30  40.0  male  First   27.7208         0
34  28.0  male  First   82.1708         0

key : ('Second', 'female')
number : 76
     age     sex   class     fare  survived
9   14.0  female  Second  30.0708         1
15  55.0  female  Second  16.0000         1
41  27.0  female  Second  21.0000         0
43   3.0  female  Second  41.5792         1
53  29.0  female  Second  26.0000         1

key : ('Second', 'male')
number : 108
     age   sex   class  fare  survived
17   NaN  male  Second  13.0         1
20  35.0  male  Second  26.0         0
21  34.0  male  Second  13.0         1
33  66.0  male  Second  10.5         0
70  32.0  male  Second  10.5         0

key : ('Third', 'female')
number : 144
     age     sex  class     fare  survived
2   26.0  female  Third   7.9250         1
8   27.0  female  Third  11.1333         1
10   4.0  female  Third  16.7000         1
14  14.0  female  Third   7.8542         0
18  31.0  female  Third  18.0000         0

key : ('Third', 'male')
number : 347
     age   sex  class     fare  survived
0   22.0  male  Third   7.2500         0
4   35.0  male  Third   8.0500         0
5    NaN  male  Third   8.4583         0
7    2.0  male  Third  21.0750         0
12  20.0  male  Third   8.0500         0

In [43]:
average = grouped_two.mean()
average

                     age        fare  survived
class  sex
First  female  34.611765  106.125798  0.968085
       male    41.281386   67.226127  0.368852
Second female  28.722973   21.970121  0.921053
       male    30.740707   19.741782  0.157407
Third  female  21.750000   16.118810  0.500000
       male    26.507589   12.661633  0.135447

In [44]:
group_3_female = grouped_two.get_group(('Third', 'female'))
group_3_female

      age     sex  class     fare  survived
2    26.0  female  Third   7.9250         1
8    27.0  female  Third  11.1333         1
10    4.0  female  Third  16.7000         1
14   14.0  female  Third   7.8542         0
18   31.0  female  Third  18.0000         0
..    ...     ...    ...      ...       ...
863   NaN  female  Third  69.5500         0
875  15.0  female  Third   7.2250         1
882  22.0  female  Third  10.5167         0
885  39.0  female  Third  29.1250         0
888   NaN  female  Third  23.4500         0

[144 rows x 5 columns]

In [46]:
grouped = df.groupby(['class'])
std_all = grouped.std()
std_all

<ipython-input-46-60972f8b0d47>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  std_all = grouped.std()

              age       fare  survived
class
First   14.802856  78.380373  0.484026
Second  14.001077  13.417399  0.500623
Third   12.495398  11.778142  0.428949

In [47]:
std_fare = grouped.fare.std()
std_fare

class
First     78.380373
Second    13.417399
Third     11.778142
Name: fare, dtype: float64

In [48]:
std_all_agg = grouped.agg('std')
std_all_agg

<ipython-input-48-90ff114807eb>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  std_all_agg = grouped.agg('std')

              age       fare  survived
class
First   14.802856  78.380373  0.484026
Second  14.001077  13.417399  0.500623
Third   12.495398  11.778142  0.428949

In [49]:
std_fare_agg = grouped.fare.agg('std')
std_fare_agg

class
First     78.380373
Second    13.417399
Third     11.778142
Name: fare, dtype: float64

In [50]:
def min_max(n):
    return n.max() - n.min()

agg_minmax = grouped.agg(min_max)
agg_minmax

<ipython-input-50-2f40695545f7>:4: FutureWarning: ['sex'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  agg_minmax = grouped.agg(min_max)

          age      fare  survived
class
First   79.08  512.3292         1
Second  69.33   73.5000         1
Third   73.58   69.5500         1

In [51]:
agg_all = grouped.agg(['min', 'max'])
agg_all

         age           sex       fare           survived
         min   max     min   max  min       max      min max
class
First   0.92  80.0  female  male  0.0  512.3292        0   1
Second  0.67  70.0  female  male  0.0   73.5000        0   1
Third   0.42  74.0  female  male  0.0   69.5500        0   1

In [56]:
import pandas as pd

df = pd.DataFrame({
    'Group' : ['A', 'A', 'B', 'B', 'A', 'B'],
    'Value' : [10, 20, 30, 40, 50, 60],
})

trans_result = df.groupby('Group')['Value'].transform('mean')
trans_result

0    26.666667
1    26.666667
2    43.333333
3    43.333333
4    26.666667
5    43.333333
Name: Value, dtype: float64

In [57]:
agg_result = df.groupby('Group')['Value'].agg(['sum', 'mean'])
agg_result

       sum       mean
Group
A       80  26.666667
B      130  43.333333

In [58]:
agg_mean = grouped.age.mean()
agg_std = grouped.age.std()

agg_mean

class
First     38.233441
Second    29.877630
Third     25.140620
Name: age, dtype: float64

In [60]:
for key, group in grouped:
    group_zscore = (group.age - agg_mean.loc[key]) / agg_std.loc[key]
    print('key :', key)
    print(group_zscore)
    print()

key : First
1     -0.015770
3     -0.218434
6      1.065103
11     1.335321
23    -0.691315
         ...
871    0.592221
872   -0.353543
879    1.200212
887   -1.299306
889   -0.826424
Name: age, Length: 216, dtype: float64

key : Second
9     -1.134029
15     1.794317
17          NaN
20     0.365855
21     0.294432
         ...
866   -0.205529
874   -0.134106
880   -0.348375
883   -0.134106
886   -0.205529
Name: age, Length: 184, dtype: float64

key : Third
0     -0.251342
2      0.068776
4      0.789041
5           NaN
7     -1.851931
         ...
882   -0.251342
884   -0.011254
885    1.109159
888         NaN
890    0.548953
Name: age, Length: 491, dtype: float64

<ipython-input-60-0ad23426e6b4>:1: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for key, group in grouped:

In [61]:
def z_score(x):
    return (x - x.mean()) / x.std()

grouped_age = grouped.age.transform(z_score)
grouped_age

0     -0.251342
1     -0.015770
2      0.068776
3     -0.218434
4      0.789041
         ...
886   -0.205529
887   -1.299306
888         NaN
889   -0.826424
890    0.548953
Name: age, Length: 891, dtype: float64

In [62]:
grouped_age = grouped.age.transform(lambda x: (x - x.mean()) / x. std())
grouped_age

0     -0.251342
1     -0.015770
2      0.068776
3     -0.218434
4      0.789041
         ...
886   -0.205529
887   -1.299306
888         NaN
889   -0.826424
890    0.548953
Name: age, Length: 891, dtype: float64

In [64]:
# filter()

def graterthan200(x):
    return len(x) >= 200

grouped_filter = grouped.filter(graterthan200)
grouped_filter.head(10)

     age     sex  class     fare  survived
0   22.0    male  Third   7.2500         0
1   38.0  female  First  71.2833         1
2   26.0  female  Third   7.9250         1
3   35.0  female  First  53.1000         1
4   35.0    male  Third   8.0500         0
5    NaN    male  Third   8.4583         0
6   54.0    male  First  51.8625         0
7    2.0    male  Third  21.0750         0
8   27.0  female  Third  11.1333         1
10   4.0  female  Third  16.7000         1

In [65]:
grouped_filter_lambda = grouped.filter(lambda x: len(x) >= 200)
grouped_filter_lambda.head(10)

     age     sex  class     fare  survived
0   22.0    male  Third   7.2500         0
1   38.0  female  First  71.2833         1
2   26.0  female  Third   7.9250         1
3   35.0  female  First  53.1000         1
4   35.0    male  Third   8.0500         0
5    NaN    male  Third   8.4583         0
6   54.0    male  First  51.8625         0
7    2.0    male  Third  21.0750         0
8   27.0  female  Third  11.1333         1
10   4.0  female  Third  16.7000         1