In [1]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')

def add_10(n):
    return n + 10

def add_two_obj(a, b):
    return a + b

print(add_10(10))
print(add_two_obj(10, 20))

20
30

In [2]:
# age와 fare 열을 선택하여 데이터프레임 만들기

df = pd.DataFrame(titanic)
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [3]:
df = df[['age', 'fare']]
df

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [5]:
df2 = titanic.loc[:, ['age', 'fare']]
df2

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [7]:
sr1 = df['age'].apply(add_10) # add_10(df['age'])
sr1.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [9]:
sr2 = df['age'].apply(add_two_obj, b=10) # 매개변수를 지정해야함
# add_two_obj(df['age'], 10)
sr2.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [10]:
sr3 = df['age'].apply(lambda n: n+10) # add_10 == lambda n: n+10
sr3.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [11]:
sr4 = df['age'].apply(lambda n: add_10(n))
sr4.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [12]:
df_map = df.applymap(add_10)
df_map

      age     fare
0    32.0  17.2500
1    48.0  81.2833
2    36.0  17.9250
3    45.0  63.1000
4    45.0  18.0500
..    ...      ...
886  37.0  23.0000
887  29.0  40.0000
888   NaN  33.4500
889  36.0  40.0000
890  42.0  17.7500

[891 rows x 2 columns]

In [14]:
df_map2 = df.apply(add_10)
df_map2

      age     fare
0    32.0  17.2500
1    48.0  81.2833
2    36.0  17.9250
3    45.0  63.1000
4    45.0  18.0500
..    ...      ...
886  37.0  23.0000
887  29.0  40.0000
888   NaN  33.4500
889  36.0  40.0000
890  42.0  17.7500

[891 rows x 2 columns]

In [15]:
df_map3 = df.applymap(add_two_obj, b=10)
df_map3

      age     fare
0    32.0  17.2500
1    48.0  81.2833
2    36.0  17.9250
3    45.0  63.1000
4    45.0  18.0500
..    ...      ...
886  37.0  23.0000
887  29.0  40.0000
888   NaN  33.4500
889  36.0  40.0000
890  42.0  17.7500

[891 rows x 2 columns]

In [16]:
df_map4 = df.applymap(lambda n: n+10)
df_map4

      age     fare
0    32.0  17.2500
1    48.0  81.2833
2    36.0  17.9250
3    45.0  63.1000
4    45.0  18.0500
..    ...      ...
886  37.0  23.0000
887  29.0  40.0000
888   NaN  33.4500
889  36.0  40.0000
890  42.0  17.7500

[891 rows x 2 columns]

In [17]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]

def missing_value(n):
    return n.isnull()

result = df.apply(missing_value, axis=1)
result.head()

     age   fare
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False

In [18]:
def max_min(n):
    return n.max() - n.min()

result = df.apply(max_min, axis=1)
result

0      14.7500
1      33.2833
2      18.0750
3      18.1000
4      26.9500
        ...
886    14.0000
887    11.0000
888     0.0000
889     4.0000
890    24.2500
Length: 891, dtype: float64

In [20]:
def missing_value(n):
    return n.isnull()

def missing_count(n):
    return missing_value(n).sum()

result = df.pipe(missing_count)
result

age     177
fare      0
dtype: int64

In [21]:
dict_data = {'c0': [1, 2, 3], 'c1': [4, 5, 6], 'c2': [7, 8, 9]}

df = pd.DataFrame(dict_data, index=['a', 'b', 'c'])
df

   c0  c1  c2
a   1   4   7
b   2   5   8
c   3   6   9

In [23]:
new_index = ['c', 'a', 'b']
ndf = df.reindex(new_index)
ndf

   c0  c1  c2
c   3   6   9
a   1   4   7
b   2   5   8

In [24]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')

df = titanic.loc[0:4, 'survived':'age']
print(df)
print()

columns = list(df.columns.values)
print(columns)
print()

columns_sorted = sorted(columns)
print(columns_sorted)
print()

ndf1 = df[columns_sorted]
print(ndf1)
print()

columns_reversed = list(reversed(columns))
print(columns_reversed)
print()

columns_reversed2 = list(reversed(columns_sorted))
print(columns_reversed2)

   survived  pclass     sex   age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0

['survived', 'pclass', 'sex', 'age']

['age', 'pclass', 'sex', 'survived']

    age  pclass     sex  survived
0  22.0       3    male         0
1  38.0       1  female         1
2  26.0       3  female         1
3  35.0       1  female         1
4  35.0       3    male         0

['age', 'sex', 'pclass', 'survived']

['survived', 'sex', 'pclass', 'age']

In [25]:
ndf2 = df[columns_reversed2]
ndf2

   survived     sex  pclass   age
0         0    male       3  22.0
1         1  female       1  38.0
2         1  female       3  26.0
3         1  female       1  35.0
4         0    male       3  35.0

In [26]:
columns_customed = ['sex', 'pclass', 'age', 'survived']
ndf3 = df[columns_customed]
ndf3

      sex  pclass   age  survived
0    male       3  22.0         0
1  female       1  38.0         1
2  female       3  26.0         1
3  female       1  35.0         1
4    male       3  35.0         0

In [27]:
df = pd.read_csv('/content/stock-data.csv')
df.head()

         Date  Close  Start   High    Low  Volume
0  2023-07-02  10100  10850  10900  10000  137977
1  2023-06-29  10700  10550  10900   9990  170253
2  2023-06-28  10400  10900  10950  10150  155769
3  2023-06-27  10900  10800  11050  10500  133548
4  2023-06-26  10800  10900  11000  10700   63039

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     object
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), object(1)
memory usage: 1.1+ KB

In [30]:
df['Date'] = df['Date'].astype('str')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     object
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), object(1)
memory usage: 1.1+ KB

In [31]:
dates = df['Date'].str.split('-')
dates

0     [2023, 07, 02]
1     [2023, 06, 29]
2     [2023, 06, 28]
3     [2023, 06, 27]
4     [2023, 06, 26]
5     [2023, 06, 25]
6     [2023, 06, 22]
7     [2023, 06, 21]
8     [2023, 06, 20]
9     [2023, 06, 19]
10    [2023, 06, 18]
11    [2023, 06, 15]
12    [2023, 06, 14]
13    [2023, 06, 12]
14    [2023, 06, 11]
15    [2023, 06, 08]
16    [2023, 06, 07]
17    [2023, 06, 05]
18    [2023, 06, 04]
19    [2023, 06, 01]
Name: Date, dtype: object

In [32]:
df['연'] = dates.str.get(0)
df['월'] = dates.str.get(1)
df['일'] = dates.str.get(2)
df.head()

         Date  Close  Start   High    Low  Volume     연   월   일
0  2023-07-02  10100  10850  10900  10000  137977  2023  07  02
1  2023-06-29  10700  10550  10900   9990  170253  2023  06  29
2  2023-06-28  10400  10900  10950  10150  155769  2023  06  28
3  2023-06-27  10900  10800  11050  10500  133548  2023  06  27
4  2023-06-26  10800  10900  11000  10700   63039  2023  06  26

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     object
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
 6   연       20 non-null     object
 7   월       20 non-null     object
 8   일       20 non-null     object
dtypes: int64(5), object(4)
memory usage: 1.5+ KB